name: CI

on:
  push:        # triggers on any branch
  pull_request: # triggers on any PR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Prepare environment
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v2.6.2

      - name: Run CI targets
        run: make ci


